[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
framework = arduino, espidf
monitor_speed = 115200
lib_ignore = 
	BLE
	BluetoothSerial
	SimpleBLE
	WiFiProv
	RainMaker
	NimBLE-Arduino
build_flags = -fexceptions
custom_component_remove =
	espressif/esp_insights
	espressif/esp_rainmaker
	espressif/rmaker_common
	espressif/rmaker_cmd_resp
	espressif/rmaker_common_events
	espressif/rmaker_console
	espressif/rmaker_system_ctrl
	espressif/rmaker_time_sync
	espressif/rmaker_work_queue
	espressif/esp_diag_data_store
	espressif/esp_diagnostics
	espressif/network_provisioning
	espressif/esp-modbus
	espressif/esp-dsp
	espressif/esp-zboss-lib
	espressif/esp-zigbee-lib
	espressif/cbor
	espressif/qrcode
	espressif/libsodium
	chmorgan/esp-libhelix-mp3

[env:esp32-c6-devkitc-1]
board = esp32-c6-devkitc-1
platform_packages =
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
lib_deps =
	h2zero/esp-nimble-cpp@2.1.0
	https://github.com/grimlokason/ESP32-BLE-CompositeHID.git
