; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
#platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
platform_packages = 
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
board = esp32-c6-devkitc-1
framework = arduino, espidf
build_flags = -fexceptions
lib_deps = tomstewart89/Callback@1.1
           #https://github.com/Mystfit/ESP32-BLE-CompositeHID
           #h2zero/esp-nimble-cpp
           #lemmingdev/ESP32-BLE-Gamepad
lib_ignore = BLE
	BluetoothSerial
	SimpleBLE
	WiFiProv
        NimBLE-Arduino
        #esp-nimble-cpp
monitor_speed = 115200
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/esp-dsp
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera
    espressif/cbor
    espressif/esp-dsp
    espressif/esp-modbus
    espressif/esp-zboss-lib
    espressif/esp-zigbee-lib
    espressif/esp_daylight
    espressif/esp_diag_data_store
    espressif/esp_diagnostics
    espressif/esp_insights
    espressif/esp_modem
    espressif/esp_rainmaker
    espressif/esp_schedule
    espressif/esp_secure_cert_mgr
    espressif/jsmn
    espressif/json_generator
    espressif/json_parser
    espressif/libsodium
    espressif/mdns
    espressif/network_provisioning
    espressif/qrcode
    espressif/rmaker_cmd_resp
    espressif/rmaker_common
    espressif/rmaker_common_events
    espressif/rmaker_console
    espressif/rmaker_system_ctrl
    espressif/rmaker_time_sync
    espressif/rmaker_work_queue
    chmorgan/esp-libhelix-mp3
    joltwallet/littlefs
