; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
#platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
framework = arduino, espidf
monitor_speed = 115200
#board_build.embed_txtfiles = 
#	managed_components/espressif__esp_insights/server_certs/https_server.crt
#	managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
#	managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
#	managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt
lib_ignore = 
	BLE
	BluetoothSerial
	SimpleBLE
	WiFiProv
build_flags = -fexceptions
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/esp-dsp
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera

[env:esp32dev]
board = esp32dev
platform_packages = 
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1

[env:esp32-c6-devkitc-1]
board = esp32-c6-devkitc-1
platform_packages = 
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
lib_deps = h2zero/esp-nimble-cpp@^2.1.0
           tomstewart89/Callback@1.1
#       https://github.com/grimlokason/ESP32-BLE-CompositeHID.git
